/**
 * Diff Syntax Highlighting Extension
 *
 * Overrides the built-in `edit` and `write` tools so their RESULT rendering
 * shows syntax-highlighted diffs:
 *
 * - `edit`: the result diff (`details.diff`, generated by the built-in
 *   execute) is rendered with the +/- prefix and line numbers in the standard
 *   diff colors, and the code content highlighted by language
 *   (pi's own cli-highlight via highlightCode + getLanguageFromPath).
 * - `write`: when writing to an EXISTING file, the old content is captured
 *   before execution and a diff (old → new) is rendered the same way. New
 *   files fall back to the built-in result rendering.
 *
 * Execution is fully delegated to the built-in tool definitions
 * (createEditToolDefinition / createWriteToolDefinition) — only rendering
 * changes. The built-in `renderCall` (live previews) is kept as-is.
 */

import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { Text } from "@earendil-works/pi-tui";
import {
  createEditToolDefinition,
  createWriteToolDefinition,
  generateDiffString,
  getLanguageFromPath,
  highlightCode,
  isToolCallEventType,
} from "@earendil-works/pi-coding-agent";
import type { ExtensionAPI, Theme } from "@earendil-works/pi-coding-agent";

/** old content of existing files captured pre-execution, keyed by toolCallId */
const writeOldContent = new Map<string, string>();

/**
 * Render a "+123 content" style diff string with diff-colored prefixes and
 * syntax-highlighted content. Mirrors pi's renderDiff line parsing.
 */
function renderHighlightedDiff(diffText: string, lang: string | undefined, theme: Theme): string {
  const out: string[] = [];
  for (const line of diffText.split("\n")) {
    const m = line.match(/^([+-\s])(\s*\d*)\s(.*)$/);
    if (!m) {
      out.push(theme.fg("toolDiffContext", line));
      continue;
    }
    const [, prefix, lineNum, content] = m;
    const colorKey =
      prefix === "-" ? "toolDiffRemoved" : prefix === "+" ? "toolDiffAdded" : "toolDiffContext";
    let body = content;
    if (lang && content) {
      const hl = highlightCode(content, lang);
      body = hl[0] ?? content;
    }
    out.push(theme.fg(colorKey, `${prefix}${lineNum} `) + body);
  }
  return out.join("\n");
}

function highlightedDiffComponent(diffText: string, lang: string | undefined, theme: Theme, context: any): Text {
  const text = (context.lastComponent as Text | undefined) ?? new Text("", 0, 0);
  text.setText(renderHighlightedDiff(diffText, lang, theme));
  return text;
}

export default function (pi: ExtensionAPI) {
  const cwd = process.cwd();

  // ------------------------------------------------------------------
  // edit: keep built-in execute, syntax-highlight the result diff
  // ------------------------------------------------------------------
  const editDef = createEditToolDefinition(cwd);
  const builtinEditRenderResult = editDef.renderResult;
  pi.registerTool({
    ...editDef,
    renderResult(result, options, theme, context) {
      const args = context.args as { path?: string; file_path?: string } | undefined;
      const rawPath = String(args?.file_path ?? args?.path ?? "");
      const lang = getLanguageFromPath(rawPath);

      if (context.isError) {
        const errText = (result.content || [])
          .filter((c: any) => c.type === "text")
          .map((c: any) => c.text || "")
          .join("\n");
        if (errText) {
          const text = (context.lastComponent as Text | undefined) ?? new Text("", 0, 0);
          text.setText(theme.fg("error", errText));
          return text;
        }
      }

      const details = (result as any).details as { diff?: string } | undefined;
      if (details?.diff) {
        return highlightedDiffComponent(details.diff, lang, theme, context);
      }
      return builtinEditRenderResult?.(result, options, theme, context) ?? new Text("", 0, 0);
    },
  });

  // ------------------------------------------------------------------
  // write: capture old content pre-execution; diff when file exists
  // ------------------------------------------------------------------
  pi.on("tool_call", async (event, ctx) => {
    if (isToolCallEventType("write", event)) {
      // file_path is from an older pi schema; keep as a runtime fallback
      const input = event.input as { path: string; content: string; file_path?: string };
      const rawPath = String(input.file_path ?? input.path ?? "");
      try {
        writeOldContent.set(event.toolCallId, await readFile(resolve(ctx.cwd, rawPath), "utf8"));
      } catch {
        // file doesn't exist yet — new file, no diff
      }
    }
    return undefined;
  });

  const writeDef = createWriteToolDefinition(cwd);
  const builtinWriteRenderResult = writeDef.renderResult;
  pi.registerTool({
    ...writeDef,
    renderResult(result, options, theme, context) {
      const args = context.args as { path?: string; file_path?: string; content?: string } | undefined;
      const rawPath = String(args?.file_path ?? args?.path ?? "");
      const lang = getLanguageFromPath(rawPath);
      const old = writeOldContent.get(context.toolCallId);
      writeOldContent.delete(context.toolCallId);
      if (old !== undefined) {
        const newContent = String(args?.content ?? "");
        const { diff } = generateDiffString(old, newContent);
        if (diff) {
          return highlightedDiffComponent(diff, lang, theme, context);
        }
      }
      return builtinWriteRenderResult?.(result, options, theme, context) ?? new Text("", 0, 0);
    },
  });
}
